### ISSUE TITLE
LOAD_PATH issues with lib/bj.rb -- not able to find active record

### ISSUE THREAD

**Issue by swishstache** [ahoward/bj#3]
I have RVM running a gemset for a project that uses BJ. Rails is vendored into the project and nearly all of the gems required are frozen into the project.

When I run the cucumber tests (rake cucumber:ok), I get an error from script/bj.

```
/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- active_record (LoadError)
    from /Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/swishstache/dev/myproject/vendor/plugins/bj/lib/bj.rb:45
    from /Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/swishstache/dev/myproject/script/bj:3
```

Line 45 of lib/bj.rb is not able to find active record. I used ruby-debug and set a breakpoint before the require. The gem path is available in the $LOAD_PATH (see formatted below). When I attempt to load it manually (while still on the breakpoint in ruby-debug) it still fails.

I see a reference to "Fubar gem_path issues" here http://codeforpeople.rubyforge.org/svn/bj/trunk/TODO  but, I don't see any details about it.

Is this a known issue?

RubyGems Environment:
- RUBYGEMS VERSION: 1.6.2
- RUBY VERSION: 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.7.0]
- INSTALLATION DIRECTORY: /Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset
- RUBY EXECUTABLE: /Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/bin/ruby
- EXECUTABLE DIRECTORY: /Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-darwin-10
- GEM PATHS:
  - /Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset
  - /Users/swishstache/.rvm/gems/ruby-1.8.7-p174@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
  - "gem" => "--no-ri --no-rdoc"
- REMOTE SOURCES:
  - http://rubygems.org/

$LOAD_PATH (formatted)

"/Users/swishstache/dev/myproject/vendor/plugins/bj/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/attachment_fu/vendor",
"/Users/swishstache/dev/myproject/vendor/plugins/acts_as_list/lib",
"/Users/swishstache/dev/myproject/vendor/gems/aws-s3-0.6.2/lib/aws",
"/Users/swishstache/dev/myproject/vendor/gems/thor-0.11.7/lib",
"/Users/swishstache/dev/myproject/vendor/gems/newrelic_rpm-2.14.1/vendor/gems/metric_parser-0.1.0.pre1/lib",
"/Users/swishstache/dev/myproject/vendor/gems/faker-0.3.0/lib",
"/Users/swishstache/dev/myproject/vendor/rails/actionmailer/lib/action_mailer/vendor/tmail-1.2.7/tmail/vendor/rchardet-1.3/lib",
"/Users/swishstache/dev/myproject/vendor/rails/actionmailer/lib/action_mailer/vendor/tmail-1.2.7",
"/Users/swishstache/dev/myproject/app/controllers/",
"/Users/swishstache/dev/myproject/app",
"/Users/swishstache/dev/myproject/app/models",
"/Users/swishstache/dev/myproject/app/controllers",
"/Users/swishstache/dev/myproject/app/helpers",
"/Users/swishstache/dev/myproject/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/webrat/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/validates_url_format_of/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/validates_email_format_of/lib",
"/Users/swishstache/dev/myproject/vendor/gems/validatable-1.6.7/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/ultrasphinx/lib",
"/Users/swishstache/dev/myproject/vendor/gems/tzinfo-0.3.23/lib",
"/Users/swishstache/dev/myproject/vendor/gems/thor-0.11.7/lib",
"/Users/swishstache/dev/myproject/vendor/gems/simplificator-rwebthumb-0.2.6/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/simple_http_auth/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/rspec-rails/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/rspec/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/resource_this/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/resource_on_demand/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/redbox/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/recaptcha/lib",
"/Users/swishstache/dev/myproject/vendor/gems/randexp-0.1.4/lib",
"/Users/swishstache/dev/myproject/vendor/gems/rack-1.1.2/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/oink/lib",
"/Users/swishstache/dev/myproject/vendor/gems/nokogiri-1.3.3/lib",
"/Users/swishstache/dev/myproject/vendor/gems/newrelic_rpm-2.14.1/lib",
"/Users/swishstache/dev/myproject/vendor/gems/net-ssh-2.0.15/lib",
"/Users/swishstache/dev/myproject/vendor/gems/net-scp-1.0.2/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/navigation_helper/lib",
"/Users/swishstache/dev/myproject/vendor/gems/mocha-0.9.7/lib",
"/Users/swishstache/dev/myproject/vendor/gems/mislav-will_paginate-2.3.11/lib",
"/Users/swishstache/dev/myproject/vendor/gems/mikehale-daemons-1.0.12.4/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/migration_test_helper/lib",
"/Users/swishstache/dev/myproject/vendor/gems/memcache-client-1.7.5/lib",
"/Users/swishstache/dev/myproject/vendor/gems/mechanize-0.9.0/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/jslint_on_rails/lib",
"/Users/swishstache/dev/myproject/vendor/gems/image_science-1.1.3/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/http_authentication/lib",
"/Users/swishstache/dev/myproject/vendor/gems/hoptoad_notifier-2.4.8/lib",
"/Users/swishstache/dev/myproject/vendor/gems/hoe-2.3.3/lib",
"/Users/swishstache/dev/myproject/vendor/gems/haml-3.0.25/lib",
"/Users/swishstache/dev/myproject/vendor/gems/geocoder-0.9.11/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/fitter_happier/lib",
"/Users/swishstache/dev/myproject/vendor/gems/fastercsv-1.4.0/lib",
"/Users/swishstache/dev/myproject/vendor/gems/faker-0.3.0/lib",
"/Users/swishstache/dev/myproject/vendor/gems/factory_girl-1.2.3/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/event_attribute/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/dom_id/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/default_order/lib",
"/Users/swishstache/dev/myproject/vendor/gems/database_cleaner-0.5.0/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/culerity/lib",
"/Users/swishstache/dev/myproject/vendor/gems/cucumber-rails-0.3.0/lib",
"/Users/swishstache/dev/myproject/vendor/gems/cucumber-0.6.2/lib",
"/Users/swishstache/dev/myproject/vendor/gems/constructor-1.0.2/lib",
"/Users/swishstache/dev/myproject/vendor/gems/chronic-0.2.3/lib",
"/Users/swishstache/dev/myproject/vendor/gems/catalogchoice-ar_mailer-2.1.6/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/cache_fu/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/busyajax/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/bj/lib",
"/Users/swishstache/dev/myproject/vendor/gems/aws-s3-0.6.2/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/attachment_fu/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/annotate_models/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/acts_as_state_machine/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/acts_as_sanitized/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/acts_as_list/lib",
"/Users/swishstache/dev/myproject/vendor/plugins/acts-as-taggable-on/lib",
"/Users/swishstache/dev/myproject/vendor/gems/ZenTest-4.1.4/lib",
"/Users/swishstache/dev/myproject/vendor/gems/RubyInline-3.8.3/lib",
"/Users/swishstache/dev/myproject/vendor/gems/RedCloth-4.2.2/lib",
"/Users/swishstache/dev/myproject/vendor",
"/Users/swishstache/dev/myproject/config/../vendor/rails/railties/lib/../builtin/rails_info/",
"/Users/swishstache/dev/myproject/app/sweepers",
"/Users/swishstache/dev/myproject/app/presenters",
"/Users/swishstache/dev/myproject/vendor/gems/adzap-ar_mailer-2.1.5",
"/Users/swishstache/dev/myproject/vendor/gems/ar-extensions-0.9.2/lib",
"/Users/swishstache/dev/myproject/vendor/gems/builder-2.1.2/lib",
"/Users/swishstache/dev/myproject/vendor/gems/mime-types-1.16/lib",
"/Users/swishstache/dev/myproject/vendor/gems/optiflag-0.6.5",
"/Users/swishstache/dev/myproject/vendor/gems/rwebthumb-0.2.6",
"/Users/swishstache/dev/myproject/vendor/gems/thor-0.9.7",
"/Users/swishstache/dev/myproject/vendor/gems/xml-simple-1.0.11/lib",
"/Users/swishstache/dev/myproject/vendor/rails/railties",
"/Users/swishstache/dev/myproject/vendor/rails/railties/lib",
"/Users/swishstache/dev/myproject/vendor/rails/activesupport/lib",
"/Users/swishstache/dev/myproject/vendor/rails/actionpack/lib",
**"/Users/swishstache/dev/myproject/vendor/rails/activerecord/lib",**
"/Users/swishstache/dev/myproject/vendor/rails/actionmailer/lib",
"/Users/swishstache/dev/myproject/vendor/rails/activeresource/lib",
"/Users/swishstache/dev/myproject/vendor/gems/cucumber-0.6.2/bin/../lib",
"/Users/swishstache/dev/myproject/vendor/rails/activesupport/lib/active_support/vendor/i18n-0.4.1",
"/Users/swishstache/dev/myproject/config/../vendor/rails/railties/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@global/gems/rake-0.8.7/lib",
"/Users/swishstache/dev/myproject/vendor/gems/memcache-client-1.7.5/bin",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/json_pure-1.5.1/lib",
"/Users/swishstache/dev/myproject/vendor/gems/nokogiri-1.3.3/ext",
"/Users/swishstache/dev/myproject/vendor/gems/optiflag-0.6.5/.",
"/Users/swishstache/dev/myproject/vendor/gems/RedCloth-4.2.2/ext",
"/Users/swishstache/dev/myproject/vendor/gems/RedCloth-4.2.2/lib/case_sensitive_require",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/term-ansicolor-1.0.5/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/polyglot-0.3.1/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/treetop-1.4.9/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/diff-lcs-1.1.2/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/columnize-0.3.2/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/linecache-0.43/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/ruby-debug-base-0.10.4/lib",
"/Users/swishstache/.rvm/gems/ruby-1.8.7-p174@mygemset/gems/ruby-debug-0.10.4/cli",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/i686-darwin10.7.0",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/site_ruby",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/vendor_ruby/1.8",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/vendor_ruby/1.8/i686-darwin10.7.0",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/vendor_ruby",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8",
"/Users/swishstache/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/i686-darwin10.7.0",
".",
"/Users/swishstache/dev/myproject/vendor/gems/newrelic_rpm-2.14.1/vendor/gems/dependency_detection-0.0.1.build/lib"

**Comment by ahoward** [comment]
On Tue, Apr 26, 2011 at 13:37, swishstache
reply@reply.github.com
wrote:

> Is this a known issue?

i haven't done _any_ work with rails 3 and bj but would greatly accept patches!

cheers.

## 

-a

we can never obtain peace in the outer world until we make peace with
ourselves. - h.h. the 14th dalai lama

**Comment by swishstache** [comment]
It's Rails 2.3.11 that's vendored (sorry, forgot to include that). When I install the rails 2.3.11 gem outside my gemset, then it works. So, I wonder if it's actually something to do with the GEM_PATH. I'll send a patch your way if I figure it out.

**Comment by ahoward** [comment]
yup - that's it.

On Tue, Apr 26, 2011 at 17:44, swishstache
reply@reply.github.com
wrote:

> It's Rails 2.3.11 that's vendored (sorry, forgot to include that). When I install the rails 2.3.11 gem outside my gemset, then it works. So, I wonder if it's actually something to do with the GEM_PATH. I'll send a patch your way if I figure it out.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ahoward/bj/issues/3#comment_1061566

## 

-a

we can never obtain peace in the outer world until we make peace with
ourselves. - h.h. the 14th dalai lama

**Comment by swishstache** [comment]
This is ancient - closing.
